[package]
name = "github-stats-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"

[lib]
path = "src/lib.rs"

[[bin]]
name = "github-stats-rs"
path = "src/main.rs"

[dependencies]
confique = "0.3.0"
dotenvy = "0.15.7"
secrecy = { version = "0.10.3", features = ["serde"] }
tracing = "0.1.40"
